### ISSUE TITLE
Establish a permanent API Structure for all projects

### ISSUE THREAD

**Issue by NWJ9PB** [NExxT-Development/SkyCore#2]

**Comment by NWJ9PB** [comment]
Duplicate of #1

**Comment by NWJ9PB** [comment]
Here will be the example json structure for `SkyScraper`
```yaml
//This is a json response

"result": {
   "status": "200", // This must use HTTP status codes
   "reason": "Proceed", // This is a custom response, It may or may not use the HTTP status code response
},

"response": {
  "anime": { // This doesnt require a **status** and **response** as tt will stop already if the request ended on 404 already
    "title": "Blend S",
    "description": "Why do I care giving this a detailed description? -NWJ9PB",
    "season": "1",
    "episode": "13",
    "studio": "A1-Pictures",
    "genre": "Maid-Cafe, lmao",
   },

  "VideoAvailability": {
    "status": "403",
    "reason": "Insufficient Permission",
  },
  
},
```
For every instances that an action will require some authentication, or some permissions, It is required to return a `status` and `reason`, regardless of what will be the output, and it depends on the origin to handle such replies, This self-standards will be changed soon
